[package]
name = "pi-brain-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The backend for the pi-brain knowledge base"
readme = "../README.md"
repository.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "pi_brain"

[[bin]]
name = "pi-brain"
path = "src/bin/main.rs"

[dependencies]
actix-cors = "0.7.1"
actix-files = "0.6"
actix-web = "4.14.0"
async-trait = "0.1.89"
anyhow = "1.0.103"
chrono.workspace = true
config = { version = "0.15.25", default-features = false, features = ["yaml"] }
hex = "0.4.3"
sha2 = "0.11.0"
serde.workspace = true
serde-aux = "4.7.0"
serde_json.workspace = true
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "sqlite",
    "macros",
    "uuid",
    "chrono",
    "migrate",
] }
thiserror = "2.0.18"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.19", features = ["attributes"] }
tracing-actix-web = "0.7"
tracing-log = "0.2.0"
tracing-bunyan-formatter = "0.3.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
uuid.workspace = true
pi-brain-shared = { path = "../shared" }

[dev-dependencies]
reqwest = { version = "0.13", features = ["json"] }
